trigger: none

pool:
  name: "linuxpool"
  demands:
    - Agent.Name -equals linuxagent

steps:
- task: CopyFiles@2
  inputs:
    SourceFolder: "/home/dockeruser/_work/1/s/"
    Contents: '**' 
    TargetFolder: "/home/dockeruser/dotnet_code"

- task: Docker@2
  displayName: 'Build Docker Image'
  inputs:
    command: 'build'
    Dockerfile: '/home/dockeruser/dotnet_code/Dockerfile'  # Path to your Dockerfile (adjust if needed)
    buildContext: '/home/dockeruser/dotnet_code/'
    tags: 'v1.0'

