trigger: none

pool:
  name: "linuxpool"
  demands:
    - Agent.Name -equals linuxagent

steps:
- task: CopyFiles@2
  displayName: "Copy files from default location"
  inputs:
    SourceFolder: "/home/devopsdockeruser/_work/1/s/"
    Contents: '**' 
    TargetFolder: "/home/devopsdockeruser/dotnet_code"
    

- task: DockerCompose@1
  displayName: "Run docker build command"
  inputs:
    containerregistrytype: 'Azure Container Registry'
    azureSubscription: 'devops-azure-connection'
    azureContainerRegistry: '{"loginServer":"prkappreg.azurecr.io", "id" : "/subscriptions/315346d8-947a-4fa6-85ba-e2a58ea2f051/resourceGroups/rg-acr/providers/Microsoft.ContainerRegistry/registries/prkapp"}'
    dockerComposeFile: '/home/devopsdockeruser/dotnet_code/docker-compose.yml'
    projectName: "prkapp"
    action: 'Run a Docker Compose command'
    dockerComposeCommand: 'build'


- task: DockerCompose@1
  displayName: "Run docker push command"
  inputs:
    containerregistrytype: 'Azure Container Registry'
    azureSubscription: 'devops-azure-connection'
    azureContainerRegistry: '{"loginServer":"prkappreg.azurecr.io", "id" : "/subscriptions/315346d8-947a-4fa6-85ba-e2a58ea2f051/resourceGroups/rg-acr/providers/Microsoft.ContainerRegistry/registries/prkapp"}'
    dockerComposeFile: '/home/devopsdockeruser/dotnet_code/docker-compose.yml'
    projectName: 'prkapp'
    action: 'Run a Docker Compose command'
    dockerComposeCommand: 'push'

- task: DockerCompose@1
  displayName: "Run container"
  inputs:
    containerregistrytype: 'Azure Container Registry'
    azureSubscription: 'devops-azure-connection'
    azureContainerRegistry: '{"loginServer":"prkappreg.azurecr.io", "id" : "/subscriptions/315346d8-947a-4fa6-85ba-e2a58ea2f051/resourceGroups/rg-acr/providers/Microsoft.ContainerRegistry/registries/prkapp"}'
    dockerComposeFile: '/home/devopsdockeruser/dotnet_code/docker-compose.yml'
    projectName: 'prkapp'
    action: 'Run a Docker Compose command'
    dockerComposeCommand: 'up'
    arguments: '-d'