trigger: none

pool:
  name: "linuxpool"
  demands:
    - Agent.Name -equals linuxagent

steps:
- task: CopyFiles@2
  inputs:
    SourceFolder: "/home/dockeruser/_work/1/s/"
    Contents: '**' 
    TargetFolder: "/home/dockeruser/dotnet_code"

- task: CmdLine@2
  inputs:
    script: "docker build -t myimage:v1.0 ."
    workingDirectory: "/home/dockeruser/dotnet_code/"
